services:
  - type: web
    name: webhook-service-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: webhook-service-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: webhook-service-redis
          type: redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          name: webhook-service-redis
          type: redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          name: webhook-service-redis
          type: redis
          property: connectionString

  - type: web
    name: webhook-service-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://webhook-service-api.onrender.com

  - type: redis
    name: webhook-service-redis
    ipAllowList: []
    plan: free

databases:
  - name: webhook-service-db
    databaseName: webhook_service
    plan: free